/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gdg_utils_Wrapper */

#ifndef _Included_com_gdg_utils_Wrapper
#define _Included_com_gdg_utils_Wrapper

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gdg_utils_Wrapper
 * Method:    newDisposableByteBuffer
 * Signature: (I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_gdg_utils_Wrapper_newDisposableByteBuffer
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_gdg_utils_Wrapper
 * Method:    getWidthPKM
 * Signature: (Ljava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_com_gdg_utils_Wrapper_getWidthPKM
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_gdg_utils_Wrapper
 * Method:    getHeightPKM
 * Signature: (Ljava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_com_gdg_utils_Wrapper_getHeightPKM
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_gdg_utils_Wrapper
 * Method:    newPixmap
 * Signature: ([JIII)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_gdg_utils_Wrapper_newPixmap
  (JNIEnv *, jclass, jlongArray, jint, jint, jint);

/*
 * Class:     com_gdg_utils_Wrapper
 * Method:    clear
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_gdg_utils_Wrapper_clear
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_gdg_utils_Wrapper
 * Method:    decodeImage
 * Signature: (Ljava/nio/ByteBuffer;ILjava/nio/ByteBuffer;IIII)V
 */
JNIEXPORT void JNICALL Java_com_gdg_utils_Wrapper_decodeImage
  (JNIEnv *, jclass, jobject, jint, jobject, jint, jint, jint, jint);

/*
 * Class:     com_gdg_utils_Wrapper
 * Method:    setBlend
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_gdg_utils_Wrapper_setBlend
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_gdg_graphics_g2d_Gdx2DPixmap
 * Method:    setScale
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_gdg_utils_Wrapper_setScale
        (JNIEnv *, jclass, jint);

/*
 * Class:     com_gdg_utils_Wrapper
 * Method:    drawPixmap
 * Signature: (JJIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_com_gdg_utils_Wrapper_drawPixmap
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_gdg_utils_Wrapper
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_gdg_utils_Wrapper_free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_gdg_utils_Wrapper
 * Method:    freeMemory
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_gdg_utils_Wrapper_freeMemory
  (JNIEnv *, jclass, jobject);


/*
 * Class:     com_gdg_utils_Wrapper
 * Method:    load
 * Signature: ([J[BII)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_gdg_utils_Wrapper_load
        (JNIEnv *, jclass, jlongArray, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
